---
title: "Illustrations for paper"
author: "Julian Barg"
date: "April 23, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r tidy}
library(tidyverse)
library(stargazer)
```

## 1. Read data

```{r read}
pace_delta_3 <- haven::read_dta("../preprocessed/pace_delta_3 2019-04-25.dta")
final_sample <- as.data.frame(subset(pace_delta_3, complete.cases(pace_delta_3)))
glimpse(final_sample)
```

## 2. Plot absolute values 

```{r plot_absolute}
illustration_1 <- final_sample %>%
  ggplot(aes(x=high_turnover_3, y=recalls_3)) +
  geom_jitter(height=0.8, width=0.1, alpha=0.4) +
  geom_smooth() +
  geom_smooth(method="lm", color="red")
print(illustration_1)
```

## 3. Plot change

```{r plot_relative}
illustration_2 <- final_sample %>%
  arrange(gvkey, year) %>%
  group_by(gvkey) %>%
  mutate(change_turnover = high_turnover_3 - lag(high_turnover_3),
         change_recalls = recalls_3 - lag(recalls_3)) %>%
    ggplot(aes(x=change_turnover, y=change_recalls)) +
    geom_jitter(height=0.5, width=0.1, alpha=0.6) +
    geom_smooth(method="loess") +
    geom_smooth(method="lm", color="red") +
    scale_x_continuous(limits=c(-1.1, 2.1)) +
    scale_y_continuous(limits=c(-15, 15))
print(illustration_2)
```

### Remove the outliers

```{r plot_without_outlier_1}
illustration_3 <- final_sample %>%
  arrange(gvkey, year) %>%
  group_by(gvkey) %>%
  mutate(change_turnover = high_turnover_3 - lag(high_turnover_3),
         recalls_change = recalls_3 - lag(recalls_3)) %>%
  filter(recalls_change > -10) %>%
    ggplot(aes(x=change_turnover, y=recalls_change)) +
    geom_jitter(height=0.5, width=0.1, alpha=0.6) +
    geom_smooth(method="loess") +
    geom_smooth(method="lm", color="red") +
    scale_x_continuous(limits=c(-1.1, 2.1)) +
    scale_y_continuous(limits=c(-15, 15))
print(illustration_3)
```

```{r plot_without_outlier_2}
illustration_4 <- final_sample %>%
  arrange(gvkey, year) %>%
  group_by(gvkey) %>%
  mutate(change_turnover = high_turnover_3 - lag(high_turnover_3),
         recalls_change = recalls_3 - lag(recalls_3)) %>%
  filter(recalls_change > -10, change_turnover != 2) %>%
    ggplot(aes(x=change_turnover, y=recalls_change)) +
    geom_jitter(height=0.5, width=0.1, alpha=0.6) +
    geom_smooth(method="loess") +
    geom_smooth(method="lm", color="red") +
    scale_x_continuous(limits=c(-1.1, 2.1)) +
    scale_y_continuous(limits=c(-15, 15))
print(illustration_4)
```

## 4. Summary statistics

```{r summary}
variable_names_formated <- c("Recalls", "High Turnover", "Revenue", "CEO Exit", "High Turnover * CEO Exit", "Elevated Turnover")

summary_statistics <- capture.output(stargazer(subset(final_sample, select = c(recalls_3, 
                                                                               high_turnover_3, 
                                                                               revenue_3, 
                                                                               ceo_exit_3, 
                                                                               ceo_and_high_turnover, 
                                                                               elevated_turnover_3)), 
                                     omit.summary.stat = c("p25", "p75"),
                                     covariate.labels = variable_names_formated,
                                     digits=2))

writeLines(summary_statistics, "illustrations/summary.tex")
```

```{r correlation}
correlation <- cor(subset(final_sample, select=c(recalls_3, 
                                                 high_turnover_3, 
                                                 revenue_3, 
                                                 ceo_exit_3,
                                                 ceo_and_high_turnover, 
                                                 elevated_turnover_3)))
correlation <- round(correlation, 2)
correlation[upper.tri(correlation)] <- ""
colnames(correlation) <- variable_names_formated
rownames(correlation) <- variable_names_formated
print(correlation)

correlation_formated <- capture.output(stargazer(correlation, float.env = "sidewaystable"))
writeLines(correlation_formated, "illustrations/correlation.tex")

```

## Results