---
title: "8. Prepare for stata"
author: "Julian Barg"
date: "April 22, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r imports}
library(tidyverse)
```

## 8.1 Read data
```{r read}
library(feather)
with_controls <- read_feather("../preprocessed/with_controls 2019-04-21.feather")

glimpse(with_controls)
```

## 8.2 Drop variables we don't need
```{r drop_wages}
with_controls <- select(with_controls, -n_employees, -n_exits, -wages_and_salaries, -r_n_d)

glimpse(with_controls)
```

## 8.3 High turnover
```{r high}
median_turnover <- quantile(with_controls$turnover, 0.5)
high_turnover <- quantile(with_controls$turnover, 0.75)

print(median_turnover)
print(high_turnover)
```

```{r n}
sum(with_controls$turnover >= median_turnover)
sum(with_controls$turnover >= high_turnover)
```

```{r cols}
with_controls$elevated_turnover <- with_controls$turnover >= median_turnover
with_controls$high_turnover <- with_controls$turnover >= high_turnover

glimpse(select(with_controls, elevated_turnover, high_turnover))
```

## 8.4 Create lagged variables
```{r lag}
with_lagged <- with_controls %>%
  arrange(gvkey, year) %>%
  group_by(gvkey) %>%
  mutate(turnover_1 = lag(turnover, 1), 
         turnover_2 = lag(turnover, 2), 
         turnover_3 = lag(turnover, 3), 
         turnover_4 = lag(turnover, 4), 
         turnover_5 = lag(turnover, 5),
         elevated_turnover_1 = lag(elevated_turnover, 1),
         elevated_turnover_2 = lag(elevated_turnover, 2),
         elevated_turnover_3 = lag(elevated_turnover, 3),
         elevated_turnover_4 = lag(elevated_turnover, 4),
         elevated_turnover_5 = lag(elevated_turnover, 5),
         high_turnover_1 = lag(high_turnover, 1),
         high_turnover_2 = lag(high_turnover, 2),
         high_turnover_3 = lag(high_turnover, 3),
         high_turnover_4 = lag(high_turnover, 4),
         high_turnover_5 = lag(high_turnover, 5),
         ceo_exit_1 = lag(ceo_exit, 1),
         ceo_exit_2 = lag(ceo_exit, 2),
         ceo_exit_3 = lag(ceo_exit, 3), 
         revenue_1 = lag(revenue, 1)) %>%
  ungroup()

glimpse(with_lagged)
```

We create a variable describing how many high/elevated turnover years a company had in the previous 3/5 years.
```{r turnover_years}
with_lagged <- with_lagged %>%
  mutate(elevated_turnover_running_3 = elevated_turnover_1 + elevated_turnover_2 + elevated_turnover_3,
         elevated_turnover_running_5 = 
           elevated_turnover_1 + elevated_turnover_2 + elevated_turnover_3 + elevated_turnover_4 + elevated_turnover_5,
         high_turnover_running_3 = high_turnover_1 + high_turnover_2 + high_turnover_3,
         high_turnover_running_5 = 
           high_turnover_1 + high_turnover_3 + high_turnover_3 + high_turnover_4 + high_turnover_5)

with_lagged <- with_lagged %>%
  rowwise() %>%
  mutate(ceo_exit_recent = as.logical(TRUE %in% c(ceo_exit_1, ceo_exit_2, ceo_exit_3)))

glimpse(select(with_lagged, 
               name,
               year,
               elevated_turnover_running_3, 
               elevated_turnover_running_5, 
               high_turnover_running_3, 
               high_turnover_running_5,
               ceo_exit,
               ceo_exit_recent))         
```

## 8.5 Calculate revenue and recalls change
```{r rev_growth}
with_lagged <- with_lagged %>%
  arrange(gvkey, year) %>%
  group_by(gvkey) %>%
  mutate(growth = revenue - lag(revenue),
         growth_running_3 = revenue - lag(revenue, 3),
         recalls_change = recalls - lag(recalls),
         recalls_change_3 = recalls - lag(recalls, 3)) %>%
  ungroup()

with_lagged <- with_lagged %>%
  arrange(gvkey, year) %>%
  group_by(gvkey) %>%
  mutate(growth_1 = lag(growth, 1)) %>%
  ungroup()

glimpse(select(with_lagged, growth, recalls_change, recalls_change_3, growth_1))
```

## 8.6 Cleanup rows and dtypes

```{r cleanup}
with_lagged <- subset(with_lagged, year > 2010)

with_lagged$gvkey <- as.factor(with_lagged$gvkey)
with_lagged$name <- as.factor(with_lagged$name)

glimpse(with_lagged)
```

## 8.7 Write to dta

```{r export}
haven::write_dta(with_lagged, paste0("../preprocessed/pace ", Sys.Date(), ".dta"))
```

## 8.8 Alternative dataset (delta = 2)
```{r delta_2}
pace_delta_2 <- with_controls %>%
  arrange(gvkey, year) %>%
  group_by(gvkey) %>%
  mutate(high_turnover_2 = lag(high_turnover) + lag(high_turnover, 2), 
         recalls_2 = recalls + lead(recalls),
         ceo_exit_2 = as.logical(lag(ceo_exit) + lag(ceo_exit, 2)),
         revenue_1 = lag(revenue)) %>%
  ungroup()

pace_delta_2 <- subset(pace_delta_2, year %in% c(2011, 2013, 2015, 2017))

pace_delta_2$gvkey <- as.factor(pace_delta_2$gvkey)
pace_delta_2$name <- as.factor(pace_delta_2$name)

glimpse(pace_delta_2)

haven::write_dta(pace_delta_2, paste0("../preprocessed/pace_delta_2 ", Sys.Date(), ".dta"))
```

## 8.8 Alternative dataset (delta = 3)
```{r delta_3}
pace_delta_3 <- with_controls %>%
  arrange(gvkey, year) %>%
  group_by(gvkey) %>%
  mutate(high_turnover_3 = lag(high_turnover) + lag(high_turnover, 2) + lag(high_turnover, 3), 
         recalls_3 = recalls + lead(recalls) + lead(recalls, 2),
         ceo_exit_3 = as.logical(lag(ceo_exit) + lag(ceo_exit, 2) + lag(ceo_exit, 3)),
         revenue_1 = lag(revenue),
         revenue_3 = revenue + lead(revenue) + lead(revenue, 2)) %>%
  ungroup()

pace_delta_3 <- subset(pace_delta_3, year %in% c(2011, 2014))

pace_delta_3$gvkey <- as.factor(pace_delta_3$gvkey)
pace_delta_3$name <- as.factor(pace_delta_3$name)

glimpse(pace_delta_3)

haven::write_dta(pace_delta_3, paste0("../preprocessed/pace_delta_3 ", Sys.Date(), ".dta"))
```